### ISSUE TITLE
Explanation of Output

### ISSUE THREAD

**Issue by tkurtzman** [KurtzmanLab/SSTMap#30]
We need to explain in supplemental materials or online what the output files are 

a) cluster files
b) clustercenterfile.pdb
c) probcenters  (also, the resnum of these should correspond to the cluster index so that they can be easily chosen) are these the most probable orientations?
d) an explanation of each of the quantities in the outputfile_hsa_summary.txt
e) an explanation of each file in the output_hsa_data directory.

**Comment by kamran-haider** [comment]
> We need to explain in supplemental materials or online what the output files are

Thanks for pointing out @tkurtzman. I think the best place for this would be the website and a statement in the paper along the lines that detailed description of output files is available at tutorials on sstmap.org
> c) probcenters (also, the resnum of these should correspond to the cluster index so that they can be easily chosen) are these the most probable orientations?

Yes, these are indeed probable configurations. 

@gosldorf Can you please make sure that the resnums are consistent with cluster index. Indeed, when I look at the file in a text editor, see example below. I noticed that atom number (column 2) and residue number (column 6) remain invariable. It would be nice to make the atom and residue numbers go sequentially :
 
```
ATOM      0 O    T3P C   0      17.556  14.484  14.234  0.00  0.00
ATOM      0 H    T3P C   0      16.686  15.382  13.381  0.00  0.00
ATOM      0 H    T3P C   0      16.965  15.381  14.566  0.00  0.00
```
It should be something like this:
```
ATOM      1 O    T3P C   1      17.556  14.484  14.234  0.00  0.00
ATOM      2 H    T3P C   1      16.686  15.382  13.381  0.00  0.00
ATOM      3 H    T3P C   1      16.965  15.381  14.566  0.00  0.00
```

This should be easily doable in your [6dimprobable](https://github.com/KurtzmanLab/SSTMap/blob/master/sstmap/scripts/6dimprobable.cpp) code. Feel free to fork the repo and then generate a pull request once you have edited the code. I will then go ahead merge and will also edit the [interface](https://github.com/KurtzmanLab/SSTMap/blob/master/sstmap/scripts/_sstmap_probableconfig.cpp) code. Also, if I understand correctly, your code generates a `temp.dat` for each cluster that contains the most probable configuration for that cluster (which are then written to `probcenters.pdb`. Instead of discarding these, I put them in separate pdb files, named `prefix_sitenumber_prob.pdb`. This allows having individual PDB files of most probable water configs for each cluster. This is probably redundant. @tkurtzman Please comment, which one of the two should we keep, a full `probcenters.pdb` or separate `*_prob.pdb` files for each cluster?

**Comment by kamran-haider** [comment]
Responding to the original comment, the explanation of outputs is now available here: http://sstmap.org/2017/05/09/undestanding-output/

If you guys are ok with this, we can then point to this in the draft or in the tutorial.

**Comment by tkurtzman** [comment]
Need to remove g_H.    Should add at some stage but low importance right now.   Also, we need to add the tables to supplemental materials for the paper.

**Comment by tkurtzman** [comment]
Also, units need to be put in the table.
