### ISSUE TITLE
Clustering number of frames

### ISSUE THREAD

**Issue by tkurtzman** [KurtzmanLab/SSTMap#55]
The algorithm seems to be using 10% of the frames up to 1000.   

I think the minimum should be 1000 frames...  It could also be the maximum...   We may just mandate that a minimum of 1000 frames need to be analyzed (I think this is reasonable).

**Comment by kamran-haider** [comment]
The minimum is set to be 10% of the total frames specified (by reading every 10th frame). This means for 100K trajectory, 10K frames are used for clustering (which is slow but is still done by the program). In my current testing plan, I am going to see how slow it gets for 100K. If it crashes due to memory issues are is too slow, I can go back to setting 1000 frames as the minimum. Either way, once initial clustering is done, the cluster centers are adjusted based on all of the frames.
